### PR TITLE
V0.2.0

### PR DESCRIPTION
**Pull request by polefishu**
Each master node and its slave nodes is managed by a statefulSet, create a headless svc for each statefulSet, and create a clusterIP service for all nodes.

* Support scaling down the Redis Cluster
* Support password change
* Support minor version upgrade

### CODE REVIEW

**Comment by zedtux** [comment]
That looks really nice! Looking for the v2!

**Comment by zedtux** [comment]
@polefishu when do you think the v0.2.0 will be finished?

**Comment by polefishu** [comment]
> @polefishu when do you think the v0.2.0 will be finished?

@zedtux Version v0.2.0 will be released next week.

**Comment by zedtux** [comment]
Awesome! I can't wait to try it !!

**Pull request merged**
